{% set name = "groovy" %}
{% set version = "4.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/groovy/archive//GROOVY_{{ version.replace(".", "_") }}.tar.gz
  sha256: 9b124a2d6bc7ed5ad3f35576ec13930610c03ec58e361b2aff967e842a98110c

build:
  noarch: generic
  number: 0

requirements:
  build:
    - graphviz
    - findutils
    - maven
    - openjdk >=17,<18
    - unzip
  run:
    - openjdk

test:
  commands:
    - groovysh --help

about:
  home: https://www.groovy-lang.org
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java-based scripting language
  dev_url: https://github.com/apache/groovy

extra:
  recipe-maintainers:
    - danielnachun
