context:
  version: "4_0_24"

package:
  name: groovy
  version: ${{ version }}

source:
  url: https://github.com/apache/groovy/archive//GROOVY_${{ version | replace(".", "_") }}.tar.gz
  sha256: b49dcc0530dfa1c7f0f2af8d51c71a83cc5c057196cd8d9fcb656abbb10c62e7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - graphviz
    - findutils
    - maven
    - openjdk >=17,<18
    - unzip
  run:
    - openjdk

tests:
  - script:
      - groovysh --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java-based scripting language
  homepage: https://www.groovy-lang.org
  repository: https://github.com/apache/groovy

extra:
  recipe-maintainers:
    - danielnachun
