context:
  version: "4_0_28"

package:
  name: groovy
  version: ${{ version }}

source:
  url: https://github.com/apache/groovy/archive//GROOVY_${{ version | replace(".", "_") }}.tar.gz
  sha256: 2c41e84fb26a91f37344af7253e0983fb28e7d9d8f82843f1dd88ad68c298a40

build:
  number: 0
  noarch: generic

requirements:
  build:
    - graphviz
    - findutils
    - maven
    - openjdk >=17,<18
    - unzip
  run:
    - openjdk

tests:
  - script:
      - groovysh --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java-based scripting language
  homepage: https://www.groovy-lang.org
  repository: https://github.com/apache/groovy

extra:
  recipe-maintainers:
    - danielnachun
