context:
  version: "4_0_25"

package:
  name: groovy
  version: ${{ version }}

source:
  url: https://github.com/apache/groovy/archive//GROOVY_${{ version | replace(".", "_") }}.tar.gz
  sha256: f9602bb3d5ff495804409681dc3fcc25187c4671c15c7238d498d656bea3e7a8

build:
  number: 0
  noarch: generic

requirements:
  build:
    - graphviz
    - findutils
    - maven
    - openjdk >=17,<18
    - unzip
  run:
    - openjdk

tests:
  - script:
      - groovysh --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java-based scripting language
  homepage: https://www.groovy-lang.org
  repository: https://github.com/apache/groovy

extra:
  recipe-maintainers:
    - danielnachun
